### ISSUE TITLE
The API method must be called from the main thread

### ISSUE THREAD

**Issue by macCesar** [hansemannn/titanium-google-maps#85]
Hi there...

On maps.createTile()... If I use any of the optional parameters.. I get this error:

**The API method must be called from the main thread**

I can't set 'run-on-main-thread' to true, because of other issues.

What can I do??

Thanks.

**P.D. clearTileCache() also throws the same error!!!!**

**Comment by hansemannn** [comment]
Hi @macCesar,

first of all, if there are issues with run-on-main-thread, please report those to [JIRA](http://jira.appcelerator.com). This is fundamentally important to improve it, since it will soon be the default in all apps, if no issues are reported (there are no open ones known, but obviously you have some).

I will push a fix for those methods and others that may are related right today, but please do me a favor and report your issues as well.

Thanks!

**Comment by hansemannn** [comment]
Fixed as part of https://github.com/hansemannn/titanium-google-maps/commit/7e1690599d96dcec2a32e4dc7c67829063c53687 in Release 3.3.2 (will be put on release page later today).

**Comment by macCesar** [comment]
Thank you very much Hans!!!

My main issue with run-on-main-thread is related to this tickets:

iOS: The first view-children not firing click-events when using run-on-main-thread https://jira.appcelerator.org/browse/TIMOB-23934
[iOS] View inside another view does not fire events https://jira.appcelerator.org/browse/TIMOB-24573

I'm waiting for SDK 6.1.0 to test it.

And again, thanks for your quick response!!

**Comment by hansemannn** [comment]
Thank you! :-) Yeah, we fixed those in 6.1.0, please try out the RC version released last week to provide feedback if something doesn't work for you so far. You may also follow some members of the core-team to stay up to date about changes being made. Thanks again for reporting!

**Comment by macCesar** [comment]
Thanks Hans, I'll try the RC version!!!
